version: "3.8"
services:
    apachenovo:
        image: httpd:alpine
        container_name: 'Apachenovo'
        ports:
            - 80:80
        volumes:
            - ./htdocs:/usr/local/apache2/htdocs/
        networks:
            - minhaConexaoPadrao

networks:
    minhaConexaoPadrao:
        driver: bridge

